zhaoli:
  pay:
    ##模板 id
    notifyMerchantTemplateId: MTRjfzTJLetdjpezc4YcDLgelN7XNpvA63ZgUpRKhXI
server:
  ##启动端口号
  port: 7071
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
## 配置微信公众号
wx:
  mp:
    configs:
      - appId: wxb9b6fb69750f3353
        secret: 3241510d2156276e8184e1be4dd2eafb
        token: zhaoli
spring:
  ##rabbitmq 相关配置
  rabbitmq:
    #连接地址
    host: 192.168.182.138
    #端口号
    port: 5672
    #账号
    username: admin
    #密码
    password: admin
    #地址
    virtual-host: /
    listener:
      simple: ## 修改配置为手动ack模式
#        acknowledge-mode: manual
        retry:
          enabled: true           # 开启消费者出现异常情况下，进行重试消费，默认false
          max-attempts: 3         # 最大重试次数，默认为3
          initial-interval: 3000  # 重试间隔时间，默认1000(单位毫秒)
  application:
    ###服务的名称
    name: zhaoli-pay
  datasource:
    password: 20020806
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhaolipay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  ##redis相关配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
  #    # 设置密码
  #    password: "123456"
mybatis-plus:
  #  #扫描mapper文件路径
  #  mapper-locations: classpath:mapper/*/*.xml
  #  #注册实体类
  #  type-aliases-package: com.study.order.pojo
  #设置配置的日志输出信息 看sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
